"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.actor_actor_graph_all_of import ActorActorGraphAllOf
from uiuc_incas_client.model.actor_to_actor_edge import ActorToActorEdge
from uiuc_incas_client.model.base_graph import BaseGraph
globals()['ActorActorGraphAllOf'] = ActorActorGraphAllOf
globals()['ActorToActorEdge'] = ActorToActorEdge
globals()['BaseGraph'] = BaseGraph
from uiuc_incas_client.model.actor_actor_graph import ActorActorGraph


class TestActorActorGraph(unittest.TestCase):
    """ActorActorGraph unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActorActorGraph(self):
        """Test ActorActorGraph"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActorActorGraph()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
