"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.array_actor_enrichment import ArrayActorEnrichment
from uiuc_incas_client.model.category_actor_enrichment import CategoryActorEnrichment
from uiuc_incas_client.model.numeric_actor_enrichment import NumericActorEnrichment
from uiuc_incas_client.model.text_actor_enrichment import TextActorEnrichment
globals()['ArrayActorEnrichment'] = ArrayActorEnrichment
globals()['CategoryActorEnrichment'] = CategoryActorEnrichment
globals()['NumericActorEnrichment'] = NumericActorEnrichment
globals()['TextActorEnrichment'] = TextActorEnrichment
from uiuc_incas_client.model.actor_enrichment import ActorEnrichment


class TestActorEnrichment(unittest.TestCase):
    """ActorEnrichment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActorEnrichment(self):
        """Test ActorEnrichment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActorEnrichment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
