"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.actor_to_message_edge import ActorToMessageEdge
globals()['ActorToMessageEdge'] = ActorToMessageEdge
from uiuc_incas_client.model.actor_message_graph_all_of import ActorMessageGraphAllOf


class TestActorMessageGraphAllOf(unittest.TestCase):
    """ActorMessageGraphAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActorMessageGraphAllOf(self):
        """Test ActorMessageGraphAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActorMessageGraphAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
