# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.6.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uiuc_incas_client
from uiuc_incas_client.models.one_of_message_enrichment_meta import OneOfMessageEnrichmentMeta  # noqa: E501
from uiuc_incas_client.rest import ApiException


class TestOneOfMessageEnrichmentMeta(unittest.TestCase):
    """OneOfMessageEnrichmentMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfMessageEnrichmentMeta(self):
        """Test OneOfMessageEnrichmentMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uiuc_incas_client.models.one_of_message_enrichment_meta.OneOfMessageEnrichmentMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
