# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.twitter_data import TwitterData  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterData(unittest.TestCase):
    """TwitterData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwitterData(self):
        """Test TwitterData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.twitter_data.TwitterData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
