"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import uiuc_incas_client
from uiuc_incas_client.api.message_api import MessageApi  # noqa: E501


class TestMessageApi(unittest.TestCase):
    """MessageApi unit test stubs"""

    def setUp(self):
        self.api = MessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_actor_enrichments_delete(self):
        """Test case for actor_enrichments_delete

        """
        pass

    def test_message_enrichments_delete(self):
        """Test case for message_enrichments_delete

        """
        pass

    def test_message_enrichments_get(self):
        """Test case for message_enrichments_get

        """
        pass

    def test_message_enrichments_post(self):
        """Test case for message_enrichments_post

        """
        pass

    def test_message_enrichments_put(self):
        """Test case for message_enrichments_put

        """
        pass

    def test_message_id_enrichments_delete(self):
        """Test case for message_id_enrichments_delete

        """
        pass

    def test_message_id_enrichments_get(self):
        """Test case for message_id_enrichments_get

        """
        pass

    def test_message_id_enrichments_post(self):
        """Test case for message_id_enrichments_post

        """
        pass

    def test_message_id_enrichments_put(self):
        """Test case for message_id_enrichments_put

        """
        pass

    def test_message_id_get(self):
        """Test case for message_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
