"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.array_message_enrichment_meta import ArrayMessageEnrichmentMeta
from uiuc_incas_client.model.category_message_enrichment_meta import CategoryMessageEnrichmentMeta
from uiuc_incas_client.model.numerical_message_enrichment_meta import NumericalMessageEnrichmentMeta
from uiuc_incas_client.model.text_message_enrichment_meta import TextMessageEnrichmentMeta
globals()['ArrayMessageEnrichmentMeta'] = ArrayMessageEnrichmentMeta
globals()['CategoryMessageEnrichmentMeta'] = CategoryMessageEnrichmentMeta
globals()['NumericalMessageEnrichmentMeta'] = NumericalMessageEnrichmentMeta
globals()['TextMessageEnrichmentMeta'] = TextMessageEnrichmentMeta
from uiuc_incas_client.model.message_enrichment_meta import MessageEnrichmentMeta


class TestMessageEnrichmentMeta(unittest.TestCase):
    """MessageEnrichmentMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageEnrichmentMeta(self):
        """Test MessageEnrichmentMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageEnrichmentMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
