# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uiuc_incas_client
from uiuc_incas_client.api.graph_api import GraphApi  # noqa: E501
from uiuc_incas_client.rest import ApiException


class TestGraphApi(unittest.TestCase):
    """GraphApi unit test stubs"""

    def setUp(self):
        self.api = GraphApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_actor_actor_graph_id_delete(self):
        """Test case for actor_actor_graph_id_delete

        """
        pass

    def test_actor_actor_graph_id_get(self):
        """Test case for actor_actor_graph_id_get

        """
        pass

    def test_actor_actor_graph_id_neighbor_get(self):
        """Test case for actor_actor_graph_id_neighbor_get

        """
        pass

    def test_actor_actor_graph_id_put(self):
        """Test case for actor_actor_graph_id_put

        """
        pass

    def test_actor_actor_graph_list_get(self):
        """Test case for actor_actor_graph_list_get

        """
        pass

    def test_actor_actor_graph_post(self):
        """Test case for actor_actor_graph_post

        """
        pass

    def test_actor_message_graph_id_delete(self):
        """Test case for actor_message_graph_id_delete

        """
        pass

    def test_actor_message_graph_id_get(self):
        """Test case for actor_message_graph_id_get

        """
        pass

    def test_actor_message_graph_id_neighbor_get(self):
        """Test case for actor_message_graph_id_neighbor_get

        """
        pass

    def test_actor_message_graph_id_put(self):
        """Test case for actor_message_graph_id_put

        """
        pass

    def test_actor_message_graph_list_get(self):
        """Test case for actor_message_graph_list_get

        """
        pass

    def test_actor_message_graph_post(self):
        """Test case for actor_message_graph_post

        """
        pass

    def test_message_message_graph_id_delete(self):
        """Test case for message_message_graph_id_delete

        """
        pass

    def test_message_message_graph_id_get(self):
        """Test case for message_message_graph_id_get

        """
        pass

    def test_message_message_graph_id_neighbor_get(self):
        """Test case for message_message_graph_id_neighbor_get

        """
        pass

    def test_message_message_graph_id_put(self):
        """Test case for message_message_graph_id_put

        """
        pass

    def test_message_message_graph_list_get(self):
        """Test case for message_message_graph_list_get

        """
        pass

    def test_message_message_graph_post(self):
        """Test case for message_message_graph_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
