"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.base_enrichment_meta import BaseEnrichmentMeta
globals()['BaseEnrichmentMeta'] = BaseEnrichmentMeta
from uiuc_incas_client.model.numerical_message_enrichment_meta import NumericalMessageEnrichmentMeta


class TestNumericalMessageEnrichmentMeta(unittest.TestCase):
    """NumericalMessageEnrichmentMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumericalMessageEnrichmentMeta(self):
        """Test NumericalMessageEnrichmentMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NumericalMessageEnrichmentMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
