"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.base_actor_enrichment import BaseActorEnrichment
from uiuc_incas_client.model.category_message_enrichment_all_of import CategoryMessageEnrichmentAllOf
globals()['BaseActorEnrichment'] = BaseActorEnrichment
globals()['CategoryMessageEnrichmentAllOf'] = CategoryMessageEnrichmentAllOf
from uiuc_incas_client.model.category_actor_enrichment import CategoryActorEnrichment


class TestCategoryActorEnrichment(unittest.TestCase):
    """CategoryActorEnrichment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategoryActorEnrichment(self):
        """Test CategoryActorEnrichment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CategoryActorEnrichment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
