# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.6.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uiuc_incas_client
from uiuc_incas_client.api.admin_api import AdminApi  # noqa: E501
from uiuc_incas_client.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_actor_post(self):
        """Test case for admin_actor_post

        """
        pass

    def test_admin_message_post(self):
        """Test case for admin_message_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
