"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.annotation import Annotation
from uiuc_incas_client.model.extra_attribute import ExtraAttribute
from uiuc_incas_client.model.links import Links
from uiuc_incas_client.model.media_resource import MediaResource
globals()['Annotation'] = Annotation
globals()['ExtraAttribute'] = ExtraAttribute
globals()['Links'] = Links
globals()['MediaResource'] = MediaResource
from uiuc_incas_client.model.actor import Actor


class TestActor(unittest.TestCase):
    """Actor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActor(self):
        """Test Actor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Actor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
