"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.actor_to_actor_edge_all_of import ActorToActorEdgeAllOf
from uiuc_incas_client.model.base_edge import BaseEdge
globals()['ActorToActorEdgeAllOf'] = ActorToActorEdgeAllOf
globals()['BaseEdge'] = BaseEdge
from uiuc_incas_client.model.actor_to_actor_edge import ActorToActorEdge


class TestActorToActorEdge(unittest.TestCase):
    """ActorToActorEdge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActorToActorEdge(self):
        """Test ActorToActorEdge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActorToActorEdge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
