"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.numeric_message_enrichment_all_of import NumericMessageEnrichmentAllOf


class TestNumericMessageEnrichmentAllOf(unittest.TestCase):
    """NumericMessageEnrichmentAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumericMessageEnrichmentAllOf(self):
        """Test NumericMessageEnrichmentAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NumericMessageEnrichmentAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
