"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.base_enrichment_meta import BaseEnrichmentMeta
globals()['BaseEnrichmentMeta'] = BaseEnrichmentMeta
from uiuc_incas_client.model.text_actor_enrichment_meta import TextActorEnrichmentMeta


class TestTextActorEnrichmentMeta(unittest.TestCase):
    """TextActorEnrichmentMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextActorEnrichmentMeta(self):
        """Test TextActorEnrichmentMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextActorEnrichmentMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
