"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.actor import Actor
from uiuc_incas_client.model.annotation import Annotation
from uiuc_incas_client.model.extra_attribute import ExtraAttribute
from uiuc_incas_client.model.geo_location import GeoLocation
from uiuc_incas_client.model.one_of_media_type_attributes import OneOfMediaTypeAttributes
globals()['Actor'] = Actor
globals()['Annotation'] = Annotation
globals()['ExtraAttribute'] = ExtraAttribute
globals()['GeoLocation'] = GeoLocation
globals()['OneOfMediaTypeAttributes'] = OneOfMediaTypeAttributes
from uiuc_incas_client.model.message import Message


class TestMessage(unittest.TestCase):
    """Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessage(self):
        """Test Message"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Message()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
