"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.message_to_message_edge import MessageToMessageEdge
globals()['MessageToMessageEdge'] = MessageToMessageEdge
from uiuc_incas_client.model.message_message_graph_all_of import MessageMessageGraphAllOf


class TestMessageMessageGraphAllOf(unittest.TestCase):
    """MessageMessageGraphAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageMessageGraphAllOf(self):
        """Test MessageMessageGraphAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageMessageGraphAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
