"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import uiuc_incas_client
from uiuc_incas_client.model.twitter_data import TwitterData
globals()['TwitterData'] = TwitterData
from uiuc_incas_client.model.one_of_media_type_attributes import OneOfMediaTypeAttributes


class TestOneOfMediaTypeAttributes(unittest.TestCase):
    """OneOfMediaTypeAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfMediaTypeAttributes(self):
        """Test OneOfMediaTypeAttributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OneOfMediaTypeAttributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
