# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.7.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import uiuc_incas_client
from uiuc_incas_client.api.segment_api import SegmentApi  # noqa: E501
from uiuc_incas_client.rest import ApiException


class TestSegmentApi(unittest.TestCase):
    """SegmentApi unit test stubs"""

    def setUp(self):
        self.api = SegmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_segment_collection_id_delete(self):
        """Test case for segment_collection_id_delete

        """
        pass

    def test_segment_collection_id_get(self):
        """Test case for segment_collection_id_get

        """
        pass

    def test_segment_collection_id_partial_put(self):
        """Test case for segment_collection_id_partial_put

        """
        pass

    def test_segment_collection_id_put(self):
        """Test case for segment_collection_id_put

        """
        pass

    def test_segment_collection_list_get(self):
        """Test case for segment_collection_list_get

        """
        pass

    def test_segment_collection_post(self):
        """Test case for segment_collection_post

        """
        pass

    def test_segment_collection_validate_post(self):
        """Test case for segment_collection_validate_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
