# flake8: noqa

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from uiuc_incas_client.api_client import ApiClient

# import Configuration
from uiuc_incas_client.configuration import Configuration

# import exceptions
from uiuc_incas_client.exceptions import OpenApiException
from uiuc_incas_client.exceptions import ApiAttributeError
from uiuc_incas_client.exceptions import ApiTypeError
from uiuc_incas_client.exceptions import ApiValueError
from uiuc_incas_client.exceptions import ApiKeyError
from uiuc_incas_client.exceptions import ApiException
