# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from uiuc_incas_client.api_client import ApiClient


class ActorApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def actor_enrichments_get(self, **kwargs):  # noqa: E501
        """actor_enrichments_get  # noqa: E501

        Returns current actor enrichment meta by providerName, enrichmentName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_enrichments_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str enrichment_name:
        :param str provider_name:
        :param str version:
        :return: ActorEnrichmentMeta
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_enrichments_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.actor_enrichments_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def actor_enrichments_get_with_http_info(self, **kwargs):  # noqa: E501
        """actor_enrichments_get  # noqa: E501

        Returns current actor enrichment meta by providerName, enrichmentName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_enrichments_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str enrichment_name:
        :param str provider_name:
        :param str version:
        :return: ActorEnrichmentMeta
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['enrichment_name', 'provider_name', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_enrichments_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'enrichment_name' in params:
            query_params.append(('enrichmentName', params['enrichment_name']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('providerName', params['provider_name']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/enrichments', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ActorEnrichmentMeta',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_enrichments_post(self, body, **kwargs):  # noqa: E501
        """actor_enrichments_post  # noqa: E501

        Creates actor enrichment meta (post after all actors have been added)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_enrichments_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichmentMeta] body: The new enrichment meta to add (required)
        :return: ActorEnrichmentMeta
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_enrichments_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_enrichments_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def actor_enrichments_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """actor_enrichments_post  # noqa: E501

        Creates actor enrichment meta (post after all actors have been added)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_enrichments_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichmentMeta] body: The new enrichment meta to add (required)
        :return: ActorEnrichmentMeta
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_enrichments_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `actor_enrichments_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/enrichments', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ActorEnrichmentMeta',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_enrichments_put(self, body, **kwargs):  # noqa: E501
        """actor_enrichments_put  # noqa: E501

        Updates actor enrichment meta (after all actors have been added) by providerName, enrichmentName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_enrichments_put(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichmentMeta] body: The new enrichment meta to update (required)
        :param str enrichment_name:
        :param str provider_name:
        :param str version:
        :return: ActorEnrichmentMeta
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_enrichments_put_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_enrichments_put_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def actor_enrichments_put_with_http_info(self, body, **kwargs):  # noqa: E501
        """actor_enrichments_put  # noqa: E501

        Updates actor enrichment meta (after all actors have been added) by providerName, enrichmentName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_enrichments_put_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichmentMeta] body: The new enrichment meta to update (required)
        :param str enrichment_name:
        :param str provider_name:
        :param str version:
        :return: ActorEnrichmentMeta
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'enrichment_name', 'provider_name', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_enrichments_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `actor_enrichments_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'enrichment_name' in params:
            query_params.append(('enrichmentName', params['enrichment_name']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('providerName', params['provider_name']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/enrichments', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ActorEnrichmentMeta',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_id_enrichments_delete(self, id, enrichment_name, provider_name, version, **kwargs):  # noqa: E501
        """actor_id_enrichments_delete  # noqa: E501

        Delete the enrichments for specific actor by type, providerName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_delete(id, enrichment_name, provider_name, version, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: Actor ID (required)
        :param str enrichment_name: (required)
        :param str provider_name: (required)
        :param str version: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_id_enrichments_delete_with_http_info(id, enrichment_name, provider_name, version, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_id_enrichments_delete_with_http_info(id, enrichment_name, provider_name, version, **kwargs)  # noqa: E501
            return data

    def actor_id_enrichments_delete_with_http_info(self, id, enrichment_name, provider_name, version, **kwargs):  # noqa: E501
        """actor_id_enrichments_delete  # noqa: E501

        Delete the enrichments for specific actor by type, providerName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_delete_with_http_info(id, enrichment_name, provider_name, version, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: Actor ID (required)
        :param str enrichment_name: (required)
        :param str provider_name: (required)
        :param str version: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'enrichment_name', 'provider_name', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_id_enrichments_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `actor_id_enrichments_delete`")  # noqa: E501
        # verify the required parameter 'enrichment_name' is set
        if ('enrichment_name' not in params or
                params['enrichment_name'] is None):
            raise ValueError("Missing the required parameter `enrichment_name` when calling `actor_id_enrichments_delete`")  # noqa: E501
        # verify the required parameter 'provider_name' is set
        if ('provider_name' not in params or
                params['provider_name'] is None):
            raise ValueError("Missing the required parameter `provider_name` when calling `actor_id_enrichments_delete`")  # noqa: E501
        # verify the required parameter 'version' is set
        if ('version' not in params or
                params['version'] is None):
            raise ValueError("Missing the required parameter `version` when calling `actor_id_enrichments_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'enrichment_name' in params:
            query_params.append(('enrichmentName', params['enrichment_name']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('providerName', params['provider_name']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/{id}/enrichments', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_id_enrichments_get(self, id, **kwargs):  # noqa: E501
        """actor_id_enrichments_get  # noqa: E501

        Returns all matched enrichment for the specific actor by type, providerName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: Actor ID (required)
        :param str enrichment_name:
        :param str provider_name:
        :param str version:
        :return: list[ActorEnrichment]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_id_enrichments_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_id_enrichments_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def actor_id_enrichments_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """actor_id_enrichments_get  # noqa: E501

        Returns all matched enrichment for the specific actor by type, providerName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: Actor ID (required)
        :param str enrichment_name:
        :param str provider_name:
        :param str version:
        :return: list[ActorEnrichment]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'enrichment_name', 'provider_name', 'version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_id_enrichments_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `actor_id_enrichments_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'enrichment_name' in params:
            query_params.append(('enrichmentName', params['enrichment_name']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('providerName', params['provider_name']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/{id}/enrichments', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ActorEnrichment]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_id_enrichments_post(self, body, id, **kwargs):  # noqa: E501
        """actor_id_enrichments_post  # noqa: E501

        Creates new enrichments for specific message  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_post(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichment] body: The new enrichment to add (required)
        :param str id: Actor ID (required)
        :return: list[ActorEnrichment]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_id_enrichments_post_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_id_enrichments_post_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def actor_id_enrichments_post_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """actor_id_enrichments_post  # noqa: E501

        Creates new enrichments for specific message  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_post_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichment] body: The new enrichment to add (required)
        :param str id: Actor ID (required)
        :return: list[ActorEnrichment]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_id_enrichments_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `actor_id_enrichments_post`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `actor_id_enrichments_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/{id}/enrichments', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ActorEnrichment]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_id_enrichments_put(self, body, enrichment_name, provider_name, version, id, **kwargs):  # noqa: E501
        """actor_id_enrichments_put  # noqa: E501

        Update the enrichments for specific actor by type, providerName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_put(body, enrichment_name, provider_name, version, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichment] body: The new enrichments to update (required)
        :param str enrichment_name: (required)
        :param str provider_name: (required)
        :param str version: (required)
        :param str id: Message ID (required)
        :return: list[ActorEnrichment]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_id_enrichments_put_with_http_info(body, enrichment_name, provider_name, version, id, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_id_enrichments_put_with_http_info(body, enrichment_name, provider_name, version, id, **kwargs)  # noqa: E501
            return data

    def actor_id_enrichments_put_with_http_info(self, body, enrichment_name, provider_name, version, id, **kwargs):  # noqa: E501
        """actor_id_enrichments_put  # noqa: E501

        Update the enrichments for specific actor by type, providerName and version  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_enrichments_put_with_http_info(body, enrichment_name, provider_name, version, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[ActorEnrichment] body: The new enrichments to update (required)
        :param str enrichment_name: (required)
        :param str provider_name: (required)
        :param str version: (required)
        :param str id: Message ID (required)
        :return: list[ActorEnrichment]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'enrichment_name', 'provider_name', 'version', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_id_enrichments_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `actor_id_enrichments_put`")  # noqa: E501
        # verify the required parameter 'enrichment_name' is set
        if ('enrichment_name' not in params or
                params['enrichment_name'] is None):
            raise ValueError("Missing the required parameter `enrichment_name` when calling `actor_id_enrichments_put`")  # noqa: E501
        # verify the required parameter 'provider_name' is set
        if ('provider_name' not in params or
                params['provider_name'] is None):
            raise ValueError("Missing the required parameter `provider_name` when calling `actor_id_enrichments_put`")  # noqa: E501
        # verify the required parameter 'version' is set
        if ('version' not in params or
                params['version'] is None):
            raise ValueError("Missing the required parameter `version` when calling `actor_id_enrichments_put`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `actor_id_enrichments_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'enrichment_name' in params:
            query_params.append(('enrichmentName', params['enrichment_name']))  # noqa: E501
        if 'provider_name' in params:
            query_params.append(('providerName', params['provider_name']))  # noqa: E501
        if 'version' in params:
            query_params.append(('version', params['version']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/{id}/enrichments', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ActorEnrichment]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def actor_id_get(self, id, **kwargs):  # noqa: E501
        """actor_id_get  # noqa: E501

        Returns specific actor by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_get(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: Actor ID (required)
        :return: Actor
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.actor_id_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.actor_id_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def actor_id_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """actor_id_get  # noqa: E501

        Returns specific actor by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.actor_id_get_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: Actor ID (required)
        :return: Actor
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method actor_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `actor_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/actor/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Actor',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
